
const upd = require('./updateTitle')

const titles = {
  "domineus": "Superdominoa",
  "etapas": "Las etapas de la historia",
  "geoclici": "Geoclic (italiano)",
  "paseo": "Un paseo por JClic",
  "geoclic": "Geoclic (català)",  
}

const titlesMain = {
  "oinarri": "Oinarrizko kontzeptuak",
  "capaonfr": "Où?",
  "norantz": "Norantz?",
  "soinuak": "Soinuak lantzeko ekintzak",
  "basetxea": "Baserria",
  "buruera": "Buruari eragin",
  "oblog_it": "Osservazione, logica, ragionamento",
  "razoa": "Observación, lóxica e razoamento",
  "abereak": "Animaliak",
  "tecladit": "Tecladit (curs de mecanografia)",
  "teclaeus": "Tecladit (mekanografia ikastaroa)",
  "teclafr": "Tecladit (cours de dactylographie)",
  "teclaga": "Tecladit (curso de mecanografia)",
  "dek": "DEK – Oinarrizko kontzeptuak",
  "teqes": "TEC – Conceptos básicos",
  "barruan": "Barruan",
  "dentro": "Dentro",
  "eupc": "Ordenagailuak",
  "gorputza": "Giza gorputza",
  "lagun": "nire lagunak, nire lorategia",
  "animalia": "Animalia Basatiak",
  "animesp": "Animales salvajes",
  "cinemaga": "Cinemática rectilinea (gl)",
  "gaelect": "Electromagnetismo",
  "landare": "Landareak",
  "plantaga": "As plantas",
  "zuhaitz": "Zuhaitzak: Hostoen bidez ezagutu",
  "alimgal": "Os alimentos e a nutrición",
  "matergal": "Os materiais",
  "zerezkoa": "Materialak",
  "ssolaga1": "O sistema solar - 1",
  "ssolaga2": "O sistema solar - 2",
  "microbio": "Microbios: moneras, protistas, hongos",
  "microgal": "Microbios: moneras, protistas, fungos",
  "eguraldi": "Eguraldia",
  "aniplaeu": "Animaliak eta landareak",
  "sentidos": "Los órganos de los sentidos",
  "neumagal": "Actividades de pneumática",
  "eusanson": "Animalien soinuak",
  "eubremen": "Bremengo musikariak",
  "musicos": "Los músicos de Bremen",
  "komikia": "Komikia",
  "koloreak": "Koloreak",
  "hitzak": "Hitzak",
  "palabgal": "As palabras",
  "tiporaga": "Tipos de oracións",
  "marineus": "Marinaren família",
  "clicmate": "Actividades de numeración para el ciclo inicial de primaria",
  "eusmat": "Lehen ziklorako zenbaketa ariketak",
  "jokzen": "Zenbakiekin jolasten",
  "crible": "Crible d’Erastosthene",
  "eratoeus": "Eratostenesen bahea",
  "eratogal": "A criba de Eratóstenes",
  "esperato": "La criba de Eratóstenes",
  "geometeu": "Geometria planoko iharduerak",
  "serieak": "Serieak",
  "seriegal": "Series",
  "comptar": "Comptar els números de l’1 al 9",
  "contagal": "Contar os números do 1 ao 9",
  "kontatu": "Kontaku 1etik 9ra zenbakiak",
  "blocsfr": "Blocs logiques",
  "blokeak": "Formak, tamainak eta koloreak",
  "eusgeom": "Zirkunferentzia eta geometriara",
  "geomes": "Circunferencias y cuerpos geométricos",
  "geomgal": "Circunferencia, círculo e corpos xeométricos",
  "matpcies": "Matemáticas en el parvulario y ciclo inicial",
  "umemat": "Haur eta Lehen Hezkuntzarako Matematika",
  "contngal": "O conto dos números",
  "cuentanu": "El cuento de los números",
  "zenbipu": "Zenbakien kontateka",
  "geoclic": "Geoclic (català)",
  "geoclice": "Geoclic (español)",
  "geoclici": "Geoclic (italiano)",
  "geoclien": "Geoclic (Englsh)",
  "geoclifr": "Geoclic (français)",
  "geoklik": "Geoklik (euskaraz)",
  "xeoclic": "Geoclic (galego)",
  "cartegal": "Producto cartesián",
  "carteusk": "Biderkaketa Cartesiarra",
  "geo2eus": "Geometriarekin jolastuko gara",
  "geo2gal": "Ímos traballar coa Xeometría",
  "fichas": "Fichas escondidas",
  "fitxak": "Fitxa ezkutatuak",
  "fitxesit": "I gettoni nascosti",
  "smh": "Sistema metriko hamartarra",
  "eumate2c": "Matematikak erdi zikloa",
  "raicegal": "Raíces cuadradas (galego)",
  "eusnumer": "1etik 100erako zenbateka",
  "numerag": "A numeración do 1 ó 100",
  "taulak2": "Biderkatzeko taulak - 1",
  "eragike": "Eragiketak",
  "operagal": "As operacións",
  "erromata": "Zenbaki erromatarrak",
  "fraccgal": "As fraccións - 1",
  "fracgal2": "As fraccións - 2",
  "zenbosoa": "Zenbaki osoak",
  "eusnum2": "Zenbakiekin jolasten – 2",
  "euformas": "Formak, tamainak eta koloreak",
  "denbora": "Denbora neurtzen",
  "tiempo": "Medimos el tiempo",
  "euencreu": "Gurutzegramak",
  "ordeneus": "Zenbakiak ordenatu",
  "domineus": "Superdominoa",
  "superdfr": "Superdomino",
  "zifrak": "Zenbaketa - 4",
  "serisefr": "Séries numériques simples",
  "seriseus": "Zenbakizko saila errazak",
  "sim_fra": "Symétries",
  "simetreu": "Simetria",
  "pasmateu": "Denborapasa matematikoak 1",
  "briteus": "Gazteentzako orkesta gida",
  "britten": "Guia d’orquestra per a joves",
  "brittesp": "Conocemos la orquesta",
  "flauta": "La flauta màgica",
  "flautaes": "La flauta mágica",
  "carnagal": "O entroido dos animáis",
  "carnaves": "Carnaval de los animales",
  "musperga": "Instrumentos de pequena percusión",
  "musikon": "Musikon",
  "urrats": "Gizakion urratsak",
  "autonoga": "As comunidades autónomas e as suas provincias",
  "casagal": "Vivimos nunha casa",
  "etxea": "Etxe batean bizi gara",
  "egipteus": "Antzinako Egipto",
  "aldatu": "Aldatuz iraun",
  "sendia": "Familia handi bat",
  "etapas": "Las etapas de la historia",
  "transpes": "Los medios de transporte",
  "transpeu": "Garraioak",
  "lan": "Lan egiten dugu...",
  "euskadi": "Euskadi (euskaraz)",
  "paisvasc": "Euskadi (en español)",
  "cone5cat": "Coneixement del medi 5è de primària",
  "ciudpueb": "Ciudad - Pueblo",
  "geoengeu": "Geografia Ingelesa",
  "daues": "Dado",
  "daueus": "Dadoa",
  "animeus3": "Animaliak",
  "pazkoa": "Pazkoa",
  "carneseu": "Inauteriak",
  "arratonh": "Era arratonha qu’escampave era escalonha",
  "kaskarin": "Sagutxo Kaskarina",
  "laratita": "La ratita presumida",
  "ratina": "A ratiña presumida",
  "inf1eus": "Informatika ESOko 1 kurtsoa",
  "jolasten": "Jolasten ikasten dut",
  "pallaseu": "Pailasoak",
  "efeus": "Gorputz-Hekuntzaren Mintegia",
  "urtarrak": "Animalia urtarrak",
  "hegazti": "Hegaztiak",
  "eusanim3": "Animaliak 3",
  "tauclies": "La tabla periódica de los elementos",
  "uart": "Vam entath uart!",
  "eufamily": "Familia",
  "eusruman": "Oinarrizko hiztegia ume errumaniarrentzat",
  "4ipuin": "Lau ipuin oso labur",
  "eukolor": "Koloreak",
  "chino": "Vocabulario básico para niños y niñas chinos",
  "txinatar": "Oinarrizko hiztegia ume xinatarrentzat",
  "arropa": "Zer jantziko dugu?",
  "roupa": "¿Que nos poñemos?",
  "eurobesp": "Eurobingo (español)",
  "eurobeus": "Eurobingo (euskaraz)",
  "eurobgal": "Eurobingo (galego)",
  "eurobin": "Eurobingo (català)",
  "fraccat": "Fraccions",
  "fraccfra": "Fractions",
  "fraccg": "Fraccións",
  "epsileu": "€psilon, €psilon! (euskaraz)",
  "epsiloga": "€psilon, €psilon! (galego)",
  "epsilon": "€psilon, €psilon! (català)",
  "divsibg": "Divisibilidade",
  "enteirg": "Os números enteiros",
  "batuketa": "99 zenbakirainoko batuketak",
  "eutrikar": "Triangeluak eta lau aldekoak (erdi zikloa)",
  "pasameus": "Denborapasa matematikoak 2",
  "osoak": "Zenbaki osoak",
  "zirkulaz": "Zirkulazio-seinaleak",
  "garraio2": "Garraiobideak 2",
  "birzikla": "Birziklatzen ikasten dugu",
  "mates5es": "Actividades de matemáticas 5º de primaria",
  "mates6es": "Actividades de matemáticas 6º de primaria",
  "prestige": "La gaviota de «a coviña»",
  "monomis": "Monomis i polinomis",
  "colorsga": "The colors (mensaxes en galego)",
  "tetraveus": "TETRAVEX: Zenbakidun buruhausgarriak",
  "greces": "El alfabeto griego",
  "paint_eu": "Zer dakizu paint programaz?",
  "buscadif": "Busca las diferencias",
  "paraboes": "Actividades Jclic sobre parábolas",
  "dali3": "Dalí 3 (català)",
  "dali3eus": "Dalí 3 (euskaraz)",
  "anigreus": "Baserriko animaliak",
  "poligoes": "Geometría plana (español)",
  "poligons": "Geometria plana (català)",
  "fru_fr": "Les fruits",
  "paseo": "Un paseo por JClic",
  "invertes": "Los animales invertebrados",
  "obser_it": "Osservazione, logica e ragionamento",
  "observa2": "Observació, lògica i raonament",
  "pacoaran": "Paco «el chato» (aranès)",
  "eusfam100": "100eko família",
  "avertes": "Animales vertebrados",
  "eumeuslo": "Ohiko luzerako neurriak",
  "medilong": "Medidas usuales de longitud",
  "henny_fr": "Pauline la poule",
  "ssola3ca": "El sistema solar (català)",
  "ssolar3": "El sistema solar (español)",
  "lectugal": "Actividades de lectoescritura (galego)",
  "emoci_eu": "Sentimenduak eta emozioak",
  "casma": "Asma infantil (català)",
  "easma": "Asma infantil (español)",
  "oreloxo": "O reloxo. Interpretación das horas do reloxo",
  "opera3es": "La ópera",
  "sudocat": "Sudoku (català)",
  "sudoit": "Sudoku (italiano)",
  "sudoku": "Sudoku (français)",
  "abakoa": "Abako",
  "l_abaces": "El ábaco",
  "histmues": "Telegrama de la historia de la música",
  "portfoeu": "Hizkuntzen portfolio europarra",
  "climaes": "El cambio climático",
  "luces": "Luces de Navidad",
  "peixo_eu": "Arrainak",
  "pirab_eu": "Piratak! Abordatzera!",
  "stjordi": "La llegenda de Sant Jordi",
  "musde_gl": "Xoga coa auga e coa música",
  "funcioes": "Funciones",
  "color_eu": "Koloreekin jolasten",
  "su_re_fr": "Apprendre à additionner et à soustraire",
  "lateraeu": "Lateralitatea eta espazio erlazioak",
  "music_eu": "Musika-Tresnak",
  "talim_eu": "Janari motak",
  "jlimp_eu": "Beti garbi jokatu",
  "temps_eu": "Zer eguraldi dugu?",
  "reci4_eu": "Zaindu dezagun gure lurra!",
  "ossos_eu": "Hezurrak eta muskuluak",
  "calcul2es": "Juguemos a contar (0 al 99)",
  "anima_eu": "Irakurketa ulermena: ANIMALMANIA II",
  "prehi_eu": "Historiaurrea",
  "festives": "Halloween y Navidad",
  "infaeng": "Learn English with Ralf!",
  "carta_es": "La carta de la Tierra",
}

for(const prj in titles){
  console.log(`Updating ${prj} title to ${titles[prj]}`)
  upd('/dades/driveClic/Public/projects', prj, titles[prj])
}

